{
    "name": "Pedidos Delivery Restaurante Casa Vieja",
    "version": "1.0.0",
    "category": "Restaurant/Delivery",
    "summary": "Gestion de pedidos a domicilio para Restaurante Casa Vieja",
    "author": "ARCM Solutions",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "restaurant_casa_vieja_base",
        "website_sale",
    ],
    "data": [
        "data/delivery_sequence.xml",
        "data/website_cleanup.xml",
        "security/ir.model.access.csv",
        "security/ir_rule.xml",
        "views/delivery_order_views.xml",
        "views/product_template_views.xml",
        "views/website_sale_templates.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
