{
    'name': 'Gestion de Cocina Restaurante Casa Vieja',
    'version': '1.0.0',
    'category': 'Restaurant/Kitchen',
    'summary': 'Tablero de cocina y gestion de ordenes preparables',
    'author': 'ARCM Solutions',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'product',
        'point_of_sale',
        'pos_restaurant',
        'restaurant_casa_vieja_base',
        'restaurant_delivery_orders',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/kitchen_sequence.xml',
        'views/kitchen_order_views.xml',
        'views/product_views.xml',
        'views/delivery_order_views.xml',
        'views/menu.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'restaurant_kitchen_management/static/src/js/kitchen_service.js',
            'restaurant_kitchen_management/static/src/js/kitchen_ready_popup.js',
            'restaurant_kitchen_management/static/src/js/product_screen_kitchen.js',
            'restaurant_kitchen_management/static/src/js/floor_screen_kitchen_status.js',
            'restaurant_kitchen_management/static/src/xml/kitchen_buttons.xml',
            'restaurant_kitchen_management/static/src/xml/kitchen_ready_popup.xml',
            'restaurant_kitchen_management/static/src/xml/kitchen_floor_badges.xml',
            'restaurant_kitchen_management/static/src/scss/kitchen_pos.scss',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
